wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.9
    code_path: code/examples/python/logger.py
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1648056208
    t:
      4: 3.9.7
      5: 0.12.9
      8:
      - 5
